### ISSUE TITLE
浏览器深色主题有的字看不清

### ISSUE THREAD

**Issue by yuyi1111** [hsyhhssyy/amiyabot-player-rating-standalone#2]
![image](https://github.com/hsyhhssyy/amiyabot-player-rating-standalone/assets/45939227/6aefd8eb-2f4a-4ef8-97ea-2a972a84e6ac)
![image](https://github.com/hsyhhssyy/amiyabot-player-rating-standalone/assets/45939227/9771e6d9-3c15-4c47-8ee1-947425e08ffb)

edge的深色没适配好，有的字看不清

**Comment by hsyhhssyy** [comment]
已修改
